name: Tests

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Restore dependencies
        run: npm i
      - name: Setup playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npm run test
        timeout-minutes: 3